[versions]
compose-compiler = "1.5.0"
appcompat = "1.7.1"
material = "1.12.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
cardview = "1.0.0"
kotlin = "2.2.0"
compose-bom = "2025.07.00"
activity-compose = "1.10.1"
shizuku = "13.1.5"
libsuperuser = "1.1.1"
gson = "2.13.1"
junit = "4.13.2"
mockito = "5.18.0"
robolectric = "4.15.1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version = "1.8.3" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "1.8.3" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
shizuku-api = { group = "moe.shizuku.api", name = "shizuku-api", version.ref = "shizuku" }
shizuku-provider = { group = "moe.shizuku.provider", name = "shizuku-provider", version.ref = "shizuku" }
libsuperuser = { group = "eu.chainfire", name = "libsuperuser", version.ref = "libsuperuser" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "13.0.0" }
